title: Jirachi Plush Archive
description: A comprehensive, evidence-based database of every officially licensed Jirachi plush
url: "https://kailyn0215.github.io"
baseurl: "/jir-archive"

collections:
  plushes:
    output: true
    permalink: /plush/:name/

defaults:
  - scope:
      path: ""
      type: "plushes"
    values:
      layout: "plush"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.xlsx"
  - README.md